<a href="https://colab.research.google.com/github/Omid-Hassasfar/MicroSchool_NITheCS_2024/blob/main/26_June_2024_MicroSchool_NITheCS_Abbas(Omid)_Hassasfar.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Micro school on Numpy!

June 26 2024 MicroSchool NITheCS
Abbas(Omid) Hassasfar Download Notebook : ...

Reach me out here: https://linktr.ee/hassasfar

## Check the pre-installed oackages and versions on Google Colab

In [1]:
# Check the python version

!python --version

Python 3.10.12


In [2]:
# List installed Python packages

!pip list

Package                          Version
-------------------------------- ---------------------
absl-py                          1.4.0
aiohttp                          3.9.5
aiosignal                        1.3.1
alabaster                        0.7.16
albumentations                   1.3.1
altair                           4.2.2
annotated-types                  0.7.0
anyio                            3.7.1
argon2-cffi                      23.1.0
argon2-cffi-bindings             21.2.0
array_record                     0.5.1
arviz                            0.15.1
astropy                          5.3.4
astunparse                       1.6.3
async-timeout                    4.0.3
atpublic                         4.1.0
attrs                            23.2.0
audioread                        3.0.1
autograd                         1.6.2
Babel                            2.15.0
backcall                         0.2.0
beautifulsoup4                   4.12.3
bidict                           0.23.1

## NumPy Package : The fundamental package for scientific computing with Python
### List vs NumPy Array.

#### Python Data Types: https://www.w3schools.com/python/python_datatypes.asp

---
---
Why it is useful:

Memory-efficient container that provides fast numerical operations.
Working with lists would quickly become very complicated if we wanted to do numerical operations on many elements at the same time, or if, for example, we want to be able to construct vectors and matrices in our programs. All of these features, and more, come with using NumPy arrays as our preferred data structure.

In [3]:
import numpy as np

In [4]:
print(np.__version__)

1.25.2


In [5]:
L1 = [-3,-2,0,-1,4]
L1

[-3, -2, 0, -1, 4]

In [6]:
L2 = [-1,-1,2,-3,5]
L2

[-1, -1, 2, -3, 5]

In [7]:
type(L1), type(L1), len(L2), len(L2)

(list, list, 5, 5)

In [8]:
# Be careful !
L1 + L2

[-3, -2, 0, -1, 4, -1, -1, 2, -3, 5]

In [9]:
L2 * 2

[-1, -1, 2, -3, 5, -1, -1, 2, -3, 5]

In [10]:
type(L1 + L2), len(L1 + L2)

(list, 10)

In [11]:
result1 =[]
for i in range(len(L1)):
    result1.append(L1[i]+L2[i])

print(" (L1 + L2) is",result1)

type(result1), len(result1)

 (L1 + L2) is [-4, -3, 2, -4, 9]


(list, 5)

In [28]:
# Another method of element-wise addition

result_list = [a + b for a, b in zip(L1, L2)]
result_list

[-4, -3, 2, -4, 9]

In [29]:
L1 + 1

TypeError: can only concatenate list (not "int") to list

In [ ]:
L1 * 4

Let's do it with NumPy Array

In [30]:
A1 = np.array([-3,-2,0,-1,4])
A1, type(A1) , len(A1), A1.shape, A1.ndim

(array([-3, -2,  0, -1,  4]), numpy.ndarray, 5, (5,), 1)

In [31]:
A1 + 2

array([-1,  0,  2,  1,  6])

In [32]:
A1 * 3

array([-9, -6,  0, -3, 12])

In [33]:
A2 = np.array([-1,-1,2,-3,5])
A2, type(A2) , len(A2)

(array([-1, -1,  2, -3,  5]), numpy.ndarray, 5)

In [34]:
print(A1 + A2)
type(A1 + A2), len(A1 + A2)

[-4 -3  2 -4  9]


(numpy.ndarray, 5)

---
---

Dot product:

In [35]:
# u2 @ v2 performs the Dot product of u2 and v2, which is the sum of the products of the corresponding elements in the arrays.
A1 @ A2

28

In [36]:
np.dot(A1,A2)

28

In [37]:
L1 @ L2 # for list we can not use @

TypeError: unsupported operand type(s) for @: 'list' and 'list'

Dot product with list!

In [38]:
SUM = 0; # summation is initially zero

for i in range(len(L1)): # iteratively access every pair with the same indices
    SUM = SUM + L1[i]*L2[i] # i-th entries are multiplied and then added to summation
print("The dot product of",L1,'and',L2,'is', SUM)

The dot product of [-3, -2, 0, -1, 4] and [-1, -1, 2, -3, 5] is 28


In [39]:
#Another method to define dot product with list!

dot_product = sum([a * b for a, b in zip(L1, L2)])
dot_product

28

---
---
Matrix multiplication with Numpy

In 2D, the first dimension corresponds to rows, the second to columns.

In [40]:
M1 = np.array([ [8 , 0 , -1 , 0 , 2], [-2 , -3 , 1 , 1 , 4], [0 , 0 , 1 , -7 , 1], [1 , 4 , -2 , 5 , 9]] )
M1

array([[ 8,  0, -1,  0,  2],
       [-2, -3,  1,  1,  4],
       [ 0,  0,  1, -7,  1],
       [ 1,  4, -2,  5,  9]])

In [42]:
type(M1), M1.shape, M1.ndim

(numpy.ndarray, (4, 5), 2)

In [43]:
M2 =  -2*M1
M2

array([[-16,   0,   2,   0,  -4],
       [  4,   6,  -2,  -2,  -8],
       [  0,   0,  -2,  14,  -2],
       [ -2,  -8,   4, -10, -18]])

In [48]:
type(M2), M2.shape, M2.ndim

(numpy.ndarray, (4, 5), 2)

In [46]:
np.multiply(M1, M2)  # Returns the element-wise matrix multiplication!

array([[-128,    0,   -2,    0,   -8],
       [  -8,  -18,   -2,   -2,  -32],
       [   0,    0,   -2,  -98,   -2],
       [  -2,  -32,   -8,  -50, -162]])

In [47]:
np.matmul(M1, M2)  # Standard matrix multiplication!

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 4 is different from 5)

In [49]:
M3 = np.array([ [8 , 0 , -1 , 0 ], [-2 , -3 , 1 , 1], [0 , 0 , 1 , -7], [1 , 4 , -2 , 5] ,[8 , -4 , -2 , 0] ] )
M3

array([[ 8,  0, -1,  0],
       [-2, -3,  1,  1],
       [ 0,  0,  1, -7],
       [ 1,  4, -2,  5],
       [ 8, -4, -2,  0]])

In [50]:
type(M3), M3.shape, M3.ndim

(numpy.ndarray, (5, 4), 2)

In [51]:
M4 = np.matmul(M1, M3)
M4

array([[ 80,  -8, -13,   7],
       [ 23,  -3, -10,  -5],
       [  1, -32,  13, -42],
       [ 77, -28, -27,  43]])

In [52]:
type(M4), M4.shape, M4.ndim

(numpy.ndarray, (4, 4), 2)

In [53]:
M5 = np.matmul(M3, M1)
M5

array([[ 64,   0,  -9,   7,  15],
       [ -9,  13,  -2,  -5,  -6],
       [ -7, -28,  15, -42, -62],
       [  5,   8,  -9,  43,  61],
       [ 72,  12, -14,  10,  -2]])

In [54]:
type(M5), M5.shape, M5.ndim

(numpy.ndarray, (5, 5), 2)

In [55]:
M1 + M2

array([[-8,  0,  1,  0, -2],
       [ 2,  3, -1, -1, -4],
       [ 0,  0, -1,  7, -1],
       [-1, -4,  2, -5, -9]])

In [55]:
M3 = np.array([ [8 , 0 , -1 , 0 ], [-2 , -3 , 1 , 1], [0 , 0 , 1 , -7], [1 , 4 , -2 , 5] ,[8 , -4 , -2 , 0] ] )
M3

A small illustrated summary of NumPy indexing and slicing.

In [56]:
M3

array([[ 8,  0, -1,  0],
       [-2, -3,  1,  1],
       [ 0,  0,  1, -7],
       [ 1,  4, -2,  5],
       [ 8, -4, -2,  0]])

In [57]:
M3[0]

array([ 8,  0, -1,  0])

In [58]:
M3[4]

array([ 8, -4, -2,  0])

In [60]:
M3[4,2]

-2

In [62]:
print(M3[:, 2])

[-1  1  1 -2 -2]


In [76]:
M6 = np.array([
    [[0, 1], [2, 3], [4, 5]],
    [[6, 7], [8, 9], [0, 1]],
    [[2, 3], [4, 5], [6, 7]],
    [[8, 9], [0, 1], [2, 3]]
] )
M6

array([[[0, 1],
        [2, 3],
        [4, 5]],

       [[6, 7],
        [8, 9],
        [0, 1]],

       [[2, 3],
        [4, 5],
        [6, 7]],

       [[8, 9],
        [0, 1],
        [2, 3]]])

In [69]:
type(M6), M6.shape, M6.ndim

(numpy.ndarray, (4, 3, 2), 3)

First Dimension (4):
This is the outermost dimension.
It indicates that there are 4 separate 2-dimensional arrays (or "slices").

Second Dimension (3):
Each of the 4 slices has 3 rows.
This dimension specifies the number of rows in each 2-dimensional array.

Third Dimension (2):
Each row in every slice has 2 columns.
This dimension specifies the number of columns in each row.

In [71]:
M6[0,2,1]

5

In [72]:
M6[3,1,:]

array([0, 1])

In [81]:
# arange

L3 = np.arange(16)
L3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [83]:
L3[2:15:3] # [start:end:step]


array([ 2,  5,  8, 11, 14])